version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: siu-postgres
    environment:
      POSTGRES_DB: siu
      POSTGRES_USER: siu
      POSTGRES_PASSWORD: siu123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siu -d siu"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
