spring:
  datasource:
    url: jdbc:postgresql://51.77.152.221:5432/postgres
    username: blockchainvalley
    password: blockchainvalley
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

server:
  forward-headers-strategy: framework

sui:
  chain:
    rpc-url: https://fullnode.devnet.sui.io:443
    contract-address: "0x807d018a1f6314da2e59a3a2df4938dea6b33e5dff945d9aee5949e69645753c" # packageId
    event-module-name: "payment"
    event-polling:
      enabled: true # 폴링 활성화
      interval-seconds: 30 # 서버도 1초 주기
      batch-size: 50
    websocket:
      enabled: false # WebSocket 비활성화
      url: "wss://fullnode.devnet.sui.io:443"
      reconnect:
        max-attempts: 10
        initial-delay: 1000
        max-delay: 30000
        backoff-multiplier: 2.0

logging:
  level:
    siu.siubackend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
