spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/siu
    username: siu
    password: siu123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
